# Generated by Django 4.1.3 on 2022-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(max_length=3, verbose_name='Day')),
                ('month', models.CharField(max_length=15, verbose_name='Month')),
                ('image', models.ImageField(upload_to='Announcements/')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Mathes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=50, verbose_name='Team_1')),
                ('team_2', models.CharField(max_length=50, verbose_name='Team_2')),
                ('date', models.CharField(max_length=70, verbose_name='Date')),
                ('venue', models.CharField(max_length=100, verbose_name='Venue')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=100, verbose_name='News')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_members', models.IntegerField(max_length=10, verbose_name='Discord_members')),
                ('twitter_members', models.IntegerField(max_length=10, verbose_name='Twitter_members')),
                ('nft_in_sake', models.IntegerField(max_length=5, verbose_name='nft_in_stake')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50, verbose_name='Team')),
                ('win', models.IntegerField(max_length=5, verbose_name='Win')),
                ('draw', models.IntegerField(max_length=5, verbose_name='Draw')),
                ('lose', models.IntegerField(max_length=5, verbose_name='Lose')),
                ('pts', models.IntegerField(max_length=10, verbose_name='Pts')),
            ],
        ),
        migrations.CreateModel(
            name='TopMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_image', models.ImageField(upload_to='TopMatches/')),
                ('team_2_image', models.ImageField(upload_to='TopMatches/')),
                ('vs', models.CharField(max_length=100, verbose_name='Vs')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TopPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TopPlayer/')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Сover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Cover/')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
            ],
        ),
    ]
