# Generated by Django 4.1.3 on 2022-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_mathes_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='day',
            field=models.IntegerField(verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='discord_members',
            field=models.IntegerField(verbose_name='Discord_members'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='nft_in_sake',
            field=models.IntegerField(verbose_name='nft_in_stake'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='twitter_members',
            field=models.IntegerField(verbose_name='Twitter_members'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='draw',
            field=models.IntegerField(verbose_name='Draw'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='lose',
            field=models.IntegerField(verbose_name='Lose'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='pts',
            field=models.IntegerField(verbose_name='Pts'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='win',
            field=models.IntegerField(verbose_name='Win'),
        ),
    ]
