# Generated by Django 4.1.3 on 2022-12-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_announcements_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='ModelAnnouncements',
        ),
        migrations.RenameModel(
            old_name='Matches',
            new_name='ModelMatches',
        ),
        migrations.RenameModel(
            old_name='NewsLine',
            new_name='ModelNewsLine',
        ),
        migrations.RenameModel(
            old_name='Statistics',
            new_name='ModelStatistics',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='ModelTeams',
        ),
        migrations.RenameModel(
            old_name='TopMatches',
            new_name='ModelTopMatches',
        ),
        migrations.RenameModel(
            old_name='TopPlayer',
            new_name='ModelTopPlayer',
        ),
        migrations.RenameModel(
            old_name='Сover',
            new_name='ModelСover',
        ),
    ]
