# Generated by Django 4.1.3 on 2022-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_nft_in_sake_modelstatistics_nft_in_stake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltopplayer',
            name='image',
            field=models.ImageField(null=True, upload_to='TopPlayer/'),
        ),
    ]
