# Generated by Django 4.1.3 on 2022-12-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_modeltopplayer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelannouncements',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='modelannouncements',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
