# Generated by Django 4.1.3 on 2022-12-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_modelannouncements_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelannouncements',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='modelmatches',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='modelnewsline',
            options={'verbose_name': 'News line'},
        ),
        migrations.AlterModelOptions(
            name='modelstatistics',
            options={'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='modelteams',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='modeltopmatches',
            options={'verbose_name': 'Top match', 'verbose_name_plural': 'Top matches'},
        ),
        migrations.AlterModelOptions(
            name='modeltopplayer',
            options={'verbose_name': 'Top player', 'verbose_name_plural': 'Top players'},
        ),
        migrations.AlterModelOptions(
            name='modelсover',
            options={'verbose_name': 'Cover', 'verbose_name_plural': 'Covers'},
        ),
    ]
