# Generated by Django 4.1.3 on 2022-12-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_modelannouncements_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelсover',
            options={},
        ),
    ]
