# Generated by Django 4.1.3 on 2022-12-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_modelсover_options_modeltopplayer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltopplayer',
            name='birthday',
            field=models.CharField(max_length=50, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='blockquote',
            field=models.TextField(null=True, verbose_name='Blockquote'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='club',
            field=models.CharField(max_length=50, null=True, verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='location',
            field=models.CharField(max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='previous_clubs',
            field=models.CharField(max_length=250, null=True, verbose_name='Clubs'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='squad_number',
            field=models.IntegerField(null=True, verbose_name='Squad_number'),
        ),
        migrations.AddField(
            model_name='modeltopplayer',
            name='text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='modeltopplayer',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
