# Generated by Django 4.1.3 on 2022-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_modeltopplayer_birthday_modeltopplayer_blockquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelannouncements',
            name='author',
            field=models.CharField(default='author', max_length=25, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='modelannouncements',
            name='blockquote',
            field=models.TextField(null=True, verbose_name='Blockquote'),
        ),
        migrations.AddField(
            model_name='modelannouncements',
            name='text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='modelannouncements',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
