# Generated by Django 4.1.3 on 2022-12-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_modelannouncements_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelannouncements',
            name='url',
        ),
    ]
