# Generated by Django 4.1.3 on 2022-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_modelannouncements_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelannouncements',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
